import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Footer from "./components/Footer/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Navbar />
        <Analytics/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
